name = input()
price = int(input())
v = int(input())
money = int(input())
print('Чек')
print(name, '-', str(v) + 'кг', '-', str(price) + 'руб/кг')
print('Итого:', str(price * v) + 'руб')
print('Внесено:', str(money) + 'руб')
print('Сдача:', str(money - price * v) + 'руб')